<?php

namespace DoctorsBundle\Repository;
use Symfony\Component\Validator\Constraints\DateTime;

/**
 * LocationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocationsRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLocationBySeance($id){
        $qb = $this->createQueryBuilder('l')
            ->select('l')
            ->innerJoin('l.calendrie','c')
            ->innerJoin('c.seances','s')
            ->where('s.id = ?2')
            ->setMaxResults(1)
            ->setParameter(2, $id);
        return $qb->getQuery()->getResult();
    }

    public function delete($id) {
        $now =  (new \DateTime())->format('Y-m-d H:i:s');
        $qb = $this->createQueryBuilder('l')
            ->update('DoctorsBundle:Locations', 'l')
            ->set('l.deleatedAt', ':d')
            ->where('l.id = ?2')
            ->setParameter('d', $now)
            ->setParameter(2, $id);
        return $qb->getQuery()->getResult();
    }

    public function search($mots) {
        $l = explode(" ", $mots);
        $crit = '';
        foreach ($l as $mot) {
            $crit.= "(d.firstName like '%" . $mot . "%' or ";
            $crit.= "d.lastName like '%" . $mot . "%' or ";
            $crit.= "l.adresse like '%" . $mot . "%' or ";
            $crit.= "l.ville like '%" . $mot . "%' or ";
            $crit.= "l.name like '%" . $mot . "%' or ";
            $crit.= "s.libelle like '%" . $mot . "%') and ";
        }
        $crit.= "l.doctor = d.id and ";
        $crit.= "l.verified = 1 and ";
        $crit.= "l.deleatedAt is NULL";
        $qb = $this->createQueryBuilder('l')
            ->select('l')
            ->innerJoin('l.doctor','d')
            ->leftJoin('d.specialities','s')
            ->where($crit)
            ->andWhere('l.deleatedAt is NULL')
            ->andWhere('l.verified = 1')
            ->orderBy('d.firstName');
        return $qb->getQuery()->getResult();
    }
}
