<?php

namespace Proxies\__CG__\DataBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Patient extends \DataBundle\Entity\Patient implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'DataBundle\\Entity\\Patient' . "\0" . 'firstname', '' . "\0" . 'DataBundle\\Entity\\Patient' . "\0" . 'lastname', '' . "\0" . 'DataBundle\\Entity\\Patient' . "\0" . 'birthday', '' . "\0" . 'DataBundle\\Entity\\Patient' . "\0" . 'gsm', '' . "\0" . 'DataBundle\\Entity\\Patient' . "\0" . 'domicile', '' . "\0" . 'DataBundle\\Entity\\Patient' . "\0" . 'travail', '' . "\0" . 'DataBundle\\Entity\\Patient' . "\0" . 'preferrednumber', '' . "\0" . 'DataBundle\\Entity\\Patient' . "\0" . 'adresse', '' . "\0" . 'DataBundle\\Entity\\Patient' . "\0" . 'sexe', '' . "\0" . 'DataBundle\\Entity\\Patient' . "\0" . 'id', '' . "\0" . 'DataBundle\\Entity\\Patient' . "\0" . 'profilPicture'];
        }

        return ['__isInitialized__', '' . "\0" . 'DataBundle\\Entity\\Patient' . "\0" . 'firstname', '' . "\0" . 'DataBundle\\Entity\\Patient' . "\0" . 'lastname', '' . "\0" . 'DataBundle\\Entity\\Patient' . "\0" . 'birthday', '' . "\0" . 'DataBundle\\Entity\\Patient' . "\0" . 'gsm', '' . "\0" . 'DataBundle\\Entity\\Patient' . "\0" . 'domicile', '' . "\0" . 'DataBundle\\Entity\\Patient' . "\0" . 'travail', '' . "\0" . 'DataBundle\\Entity\\Patient' . "\0" . 'preferrednumber', '' . "\0" . 'DataBundle\\Entity\\Patient' . "\0" . 'adresse', '' . "\0" . 'DataBundle\\Entity\\Patient' . "\0" . 'sexe', '' . "\0" . 'DataBundle\\Entity\\Patient' . "\0" . 'id', '' . "\0" . 'DataBundle\\Entity\\Patient' . "\0" . 'profilPicture'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Patient $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setFirstname($firstname)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFirstname', [$firstname]);

        return parent::setFirstname($firstname);
    }

    /**
     * {@inheritDoc}
     */
    public function getFirstname()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFirstname', []);

        return parent::getFirstname();
    }

    /**
     * {@inheritDoc}
     */
    public function setLastname($lastname)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastname', [$lastname]);

        return parent::setLastname($lastname);
    }

    /**
     * {@inheritDoc}
     */
    public function getLastname()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastname', []);

        return parent::getLastname();
    }

    /**
     * {@inheritDoc}
     */
    public function setBirthday($birthday)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBirthday', [$birthday]);

        return parent::setBirthday($birthday);
    }

    /**
     * {@inheritDoc}
     */
    public function getBirthday()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBirthday', []);

        return parent::getBirthday();
    }

    /**
     * {@inheritDoc}
     */
    public function setGsm($gsm)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGsm', [$gsm]);

        return parent::setGsm($gsm);
    }

    /**
     * {@inheritDoc}
     */
    public function getGsm()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGsm', []);

        return parent::getGsm();
    }

    /**
     * {@inheritDoc}
     */
    public function setDomicile($domicile)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDomicile', [$domicile]);

        return parent::setDomicile($domicile);
    }

    /**
     * {@inheritDoc}
     */
    public function getDomicile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDomicile', []);

        return parent::getDomicile();
    }

    /**
     * {@inheritDoc}
     */
    public function setTravail($travail)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTravail', [$travail]);

        return parent::setTravail($travail);
    }

    /**
     * {@inheritDoc}
     */
    public function getTravail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTravail', []);

        return parent::getTravail();
    }

    /**
     * {@inheritDoc}
     */
    public function setPreferrednumber($preferrednumber)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPreferrednumber', [$preferrednumber]);

        return parent::setPreferrednumber($preferrednumber);
    }

    /**
     * {@inheritDoc}
     */
    public function getPreferrednumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPreferrednumber', []);

        return parent::getPreferrednumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresse($adresse)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresse', [$adresse]);

        return parent::setAdresse($adresse);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresse', []);

        return parent::getAdresse();
    }

    /**
     * {@inheritDoc}
     */
    public function setSexe($sexe)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSexe', [$sexe]);

        return parent::setSexe($sexe);
    }

    /**
     * {@inheritDoc}
     */
    public function getSexe()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSexe', []);

        return parent::getSexe();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setProfilPicture(\DataBundle\Entity\Media $profilPicture = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProfilPicture', [$profilPicture]);

        return parent::setProfilPicture($profilPicture);
    }

    /**
     * {@inheritDoc}
     */
    public function getProfilPicture()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfilPicture', []);

        return parent::getProfilPicture();
    }

}
